name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: 'stable'
      - run: flutter pub get
      - name: Tests
        run: flutter test
      - name: Build
        run: flutter build web
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}
        run: |
          cd build/
          git clone https://user:$GITHUB_TOKEN@github.com/radianteam/radianteam.github.io.git
          cd radianteam.github.io/
          cp -r ../web/ ./
          git commit -m "autodeploy"
          git push origin main --set-upstream https://user:$GITHUB_TOKEN@github.com/radianteam/radianteam.github.io.git
